{% set version = "2.0.13" %}

package:
  name: bob.db.atnt
  version: {{ version }}

source:
  fn: bob.db.atnt-{{ version }}.zip
  md5: 524bb523eeac610853246d756c2e64a1
  url: https://pypi.io/packages/source/b/bob.db.atnt/bob.db.atnt-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.db.base

  run:
    - python
    - bob.db.base

test:
  commands:
    - nosetests -sv bob.db.atnt

  imports:
    - bob
    - bob.db
    - bob.db.atnt

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: ATNT/ORL Database Access API for Bob

extra:
  recipe-maintainers:
    - 183amir
